apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: organization
  labels:
    app: organization
spec:
  strategy:
    canary:
      steps:
        - setWeight: 25
        - pause: {duration: 30s}
        - setWeight: 50
        - pause: {duration: 30s}
        - setWeight: 75
        - pause: {duration: 30s}
  selector:
    matchLabels:
      app: organization
  template:
    metadata:
      labels:
        app: organization
    spec:
      serviceAccountName: api-service-account
      containers:
        - name: organization
          image: vmware/organization:1.1
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
          resources:
            requests:
              cpu: "0.2"
              memory: 384Mi
            limits:
              cpu: "1.0"
              memory: 512Mi
          readinessProbe:
            httpGet:
              port: http
              path: /actuator/health
            initialDelaySeconds: 60
            timeoutSeconds: 2
            periodSeconds: 20
            failureThreshold: 5
          livenessProbe:
            httpGet:
              port: http
              path: /actuator/info
            initialDelaySeconds: 60
            timeoutSeconds: 2
            periodSeconds: 20
            failureThreshold: 5
          volumeMounts:
            - name: mongodb
              mountPath: /etc/secretspot
      volumes:
        - name: mongodb
          secret:
            secretName: organization
