apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongodb
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/IKauedev/spring-microservices-gitops.git
    targetRevision: master
    path: k8s/mongodb
  destination:
    server: https://kubernetes.default.svc
    namespace: mongo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
